name: Build Image

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: example-container-app/app

on:
    workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}
          # Always generate latest tag (https://github.com/docker/metadata-action#latest-tag)
          flavor: latest=true
          # Sha tag is used in udpate_deploy_file job below 
          tags: |
            type=sha
            type=ref,event=pr 
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        # Support for multiplatform build. Using for dev debugging
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
              
      - # Support for multiplatform build. Using for dev debugging
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set timestamp for label
        id: build
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        
      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.desciption="Built from ${{github.ref_name}}"
            org.opencontainers.image.created=${{ steps.build.outputs.timestamp }}
            org.opencontainers.image.source=${{github.repositoryUrl}}

