name: Delete gitops branch

env:
  GITOPS_REPO: 'MonicaG/example-container-app-gitops'

on:
  pull_request:
    types: [unlabeled, closed]
    branches: [ "main" ]
  
jobs:
  close-gitops-pr:
    if: ${{ (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview')) || ( github.event.action == 'unlabeled' && github.event.label.name == 'preview' ) }}
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: 'auto-updates-${{ github.event.pull_request.number }}'

    steps:
      - name: Setup gitops repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v4   
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          token: ${{ secrets.PR_PAT }}

      - name: Delete branch in gitops
        run: |
          git push origin --delete ${{ env.BRANCH_NAME }}
          



