name: Build and update gitops repo for pr

env:
  TARGET_FILE: 'values.pr.yaml'
  WORKING_DIR: 'chart'
  YAML_PROPERTY_PATH: '.image.tag'
  GITOPS_REPO: 'MonicaG/example-container-app-gitops'

on:
  pull_request:
    types: [synchronize, reopened, labeled]
    branches: [ "main" ]

jobs:
  call-build-workflow:
    if: contains(github.event.pull_request.labels.*.name, 'preview') && github.event.pull_request.state == 'open'
    uses: ./.github/workflows/build.yaml
    
  update-gitops-pr-file:
    if: contains(github.event.pull_request.labels.*.name, 'preview') && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    needs: call-build-workflow

    steps:
      - name: Setup gitops repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v4   
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          # fetch depth 0 gets all branches and histories. The workflow needs to get the
          # branches because the workflow may run if there were multiple commits to the PR.
          # It needs to checkout the existing branch and update it, rather than creating a 
          # new branch and then getting an error when it pushes to the remote and sees there
          # is an existing branch
          fetch-depth: 0

      - name: Get short sha
        run: 
          short_name=$(./.github/scripts/get-short-sha.yaml ${{ github.sha }} )
          echo "GITHUB_SHA_SHORT=$short_name" >> $GITHUB_ENV

      - name: 'Get branch name'
        run: |
          branch_name=$(./.github/scripts/get-short-sha.sh ${{ github.event.pull_request.number }})
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: 'Configure git'
      # From https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

     

      - name: 'Create or checkout branch'
        run: |
          git checkout ${{ env.BRANCH_NAME }} || git checkout -b ${{ env.BRANCH_NAME }}       

      - name: Update image tag
        run: |
          cd ${{ env.WORKING_DIR }}
          yq -i '${{ env.YAML_PROPERTY_PATH }} = "${{ env.GITHUB_SHA_SHORT }}"' ${{ env.TARGET_FILE }}

      - name: 'Check for changes'
        id: check_for_changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
              echo "No changes"
              echo "HAS_CHANGES=0" >> $GITHUB_OUTPUT
          else
              echo "Has changes"
              echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push update
        if: ${{ steps.check_for_changes.outputs.HAS_CHANGES == 1 }}
        run: |
          git commit -am "Update image tag for dev"
          git push origin $BRANCH_NAME
