name: Build and update gitops repo

env:
  TARGET_FILE: 'values.yaml'
  WORKING_DIR: 'chart'
  YAML_PROPERTY_PATH: '.image.tag'

on:
  push:
    paths-ignore:
        - 'README.md'
        - '.github/**'
    branches: [ '**' ]
  workflow_dispatch:
    
jobs:
  should-deploy:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_DEPLOY: ${{ steps.should_deploy.outputs.SHOULD_DEPLOY }}
    steps:
      - name: Check if this workflow should deploy
        id: should_deploy
        run: |
          should_deploy=false
          if ${{ github.event_name != 'pull_request' }}; then
            should_deploy=true
          fi
          echo "SHOULD_DEPLOY=$should_run" >> "$GITHUB_OUTPUT"
  call-build-workflow:
    uses: ./.github/workflows/build.yaml

  get-short-sha:
    if: needs.should-deploy.outputs.SHOULD_DEPLOY == 'true'
    uses: ./.github/workflows/get-short-sha.yaml
    
  update-gitops-file:
    if: needs.should-deploy.outputs.SHOULD_DEPLOY == 'true'
    runs-on: ubuntu-latest
    needs: [call-build-workflow, get-short-sha]

    steps:
      
      - name: Setup gitops repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v4   
        with:
          repository: MonicaG/example-container-app-gitops
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
      
      - name: 'Configure git'
      # From https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
    

      - name: Update image tag
        run: |
          cd ${{ env.WORKING_DIR }}
          yq -i '${{ env.YAML_PROPERTY_PATH }} = "${{ needs.get-short-sha.outputs.SHORT_SHA }}"' ${{ env.TARGET_FILE }}
    
      - name: Commit and push update
        run: |
          git commit -am "Update image tag for dev"
          git push origin
